### ISSUE TITLE
Argless flags AKA the None key in the dict not actually updating. 

### ISSUE THREAD

**Issue by i-am-zaidali** [MenuDocs/Typed-Flags#3]
if an argless flag gets nested between two proper flags, the flag doesnt get merged with the first flag's args, it does properly get removed, but it does not get added to the argless list. It is just purely ignored. 

For overview i changed the delim to a " "(space) and then ran a command:
```python
@commands.command()
async def test(self, ctx, *, args:TypedFlagsSubclass):
    print(args)
```
```
[p]test --message this is a message --argless --last this is the last flag
```

Output is:

{"message": "this is a message", "last": "this is the last flag"}

the --argless does get removes but it doesnt end up in the None key. must be something i did wrong or maybe an actual bug so wanted to inform.

**Comment by Skelmis** [comment]
This should be resolved in the new version. The issue was using `" "` as a delim would throw logic errors
